### PR TITLE
shadow cljs fix

### PR DESCRIPTION
**Pull request by rksm**
I believe that this fixes https://github.com/clojure-emacs/clj-suitable/issues/15. I'll test this some and would invite others testing as well.

### CODE REVIEW

**Review by arichiardi — APPROVED** [review]
LGTM - haven't tried it though

**Comment by bbatsov** [comment]
Looks good to me as well - at the very least this is no longer going to blow up with shadow, even if it turns out the completion doesn't work properly. I guess @thheller can potentially confirm if we're using the right shadow-cljs API right now. 

Other than this - seems you've reflowed the entire README (I see most like breaks are gone), so it's hard to understand what are the documentation changes, but I'll assume those are fine.

I was thinking it will be nice if there was a section in the docs about hacking on suitable - should be useful to potential contributors.

**Comment by bbatsov** [comment]
One more thing - if this API didn't exist before shadow 2.10, we should probably guard against this and just return an empty list of candidates.

**Comment by thheller** [comment]
LGTM. I'll make sure that `cljs-eval` API fn stays alive and functional.

**Comment by rksm** [comment]
@bbatsov the pure diff of README.md, only minor changes. Sorry the line breaks did bother me.

Screen Shot 2021-04-18 at 1 42 18 AM

**Comment by bbatsov** [comment]
I saw you already cut 0.4, so I guess it's time to merge this branch. Big thanks for working on this!

**Pull request merged**
