### PR TITLE
Draft CI

### PR DESCRIPTION
**Pull request by vemv**
Drafts a CI setup.

I got `make test` working locally, however it fails on Circle: https://app.circleci.com/pipelines/github/reducecombine/clj-suitable/3/workflows/8ece7e9e-fe23-42ec-a76a-15db36cb842f/jobs/36

The failure in question might ring a bell:

> `Syntax error compiling at (REPL:1:1).\nNo such namespace: js\n"`

Thoughts? @rksm 

...at first it looked like improving the `RELEASE` dependencies would fix that (it certainly did for me locally), no luck on Circle though.

Finally it would be nice to add the project to https://app.circleci.com/pipelines/github/clojure-emacs in the meantime; I can't do that and would save me the temp fork. @bbatsov

### CODE REVIEW

**Comment by bbatsov** [comment]
Sure, I've enabled the project on CircleCI.

**Comment by vemv** [comment]
Thanks! Retriggered a build, it's still failing.

Sometimes the test failure is due to a `No such namespace: js` error. Other times I'm getting an empty map back with no error but no data either.

**Comment by vemv** [comment]
Build green finally 😃

Of all things, it was the chosen port what was failing: `3000` worked locally but oddly enough not on Circle.

Ready for review

**Comment by bbatsov** [comment]
Looks good to me! Thanks for tackling this!

**Pull request merged**
