### PR TITLE
Don't exclude enumerable properties from `Object`

### LINKED ISSUE #45: Regression - enumberable
https://clojurians.slack.com/archives/C0617A8PQ/p1702526959241879

### PR DESCRIPTION
**Pull request by vemv**
> Fixes https://github.com/clojure-emacs/clj-suitable/issues/45

### CODE REVIEW

**Comment by vemv** [comment]
@rrudakov - review welcome

Nested Object properties were being excluded from completions.

So I opted to whitelist String and Array. Perhaps some other category should be included?

**Comment by roman-rudakov** [comment]
Thanks for the ping @vemv. 

Interesting case, are those properties for nested objects also enumerable?

I will take a better look in the evening.

**Comment by rrudakov** [comment]
Oops, accidentally posted from my working account :)

**Comment by rrudakov** [comment]
@vemv I'm not sure that it's a proper fix, if I run new tests with the old code, all tests pass. Have you tried running tests without your fix?

**Comment by vemv** [comment]
I think the fix is proper, but we could add a test case for what actually broke (i.e. objects).

(Good catch!)

**Comment by rrudakov** [comment]
I'm trying to understand what does enumerable and nested object methods have in common :)

**Comment by vemv** [comment]
I see, there's the possibility that I'm fixing nothing, we cannot be sure until the remaining test is written.

I was operating under the assumption that https://github.com/clojure-emacs/clj-suitable/pull/42 broke things, but it could have been some other commit.

**Comment by rrudakov** [comment]
I'll try to come up with some relevant tests.

**Comment by rrudakov** [comment]
In the `*nrepl-messages..` buffer I can see to following request and response:
```
(-->
  id                        "96"
  op                        "complete"
  session                   "b63a974c-7b32-4289-aa45-81be6896f56b"
  time-stamp                "2024-01-04 19:48:57.593459376"
  context                   "(__prefix__)"
  enhanced-cljs-completion? "t"
  ns                        #("nl.alenkinaskazka.core" 0 22 (face font-lock-type-face cider-block-dynamic-font-lock t cider-locals nil fontified t))
  prefix                    "js/document."
)
(<--
  id          "96"
  session     "b63a974c-7b32-4289-aa45-81be6896f56b"
  time-stamp  "2024-01-04 19:48:57.638230221"
  completions ((dict "candidate"
       #("js/document.constructor" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.toString" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.toLocaleString" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.valueOf" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.hasOwnProperty" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.isPrototypeOf" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.propertyIsEnumerable" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.__defineGetter__" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.__defineSetter__" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.__lookupGetter__" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.__lookupSetter__" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function")
 (dict "candidate"
       #("js/document.__proto__" 0 1
         (ns "js" type "function"))
       "ns" "js" "type" "function"))
  status      ("done")
)
```

How can I reproduce it in unit tests? I tried:
```clojure
(message {:op      "complete"
                                     :ns      "cljs.user"
                                     :symbol  "js/document."
                                     :context "(__prefix__)"})
```

but I'm getting an empty list of candidates. Is `symbol` the same as `prefix`?

**Comment by vemv** [comment]
It's probably because `suitable.complete-for-nrepl-test` is written against the Node runtime, not the web

(it took me a while to realise!)

**Comment by rrudakov** [comment]
Good to know.

I've installed the fixed version locally. Looks like it works well and fixes the problem:

image

And enumerables for strings and arrays are filtered out:

image

I don't have in mind any other possible candidates to include. If I find something I'll create another PR.

**Comment by vemv** [comment]
I verified this works using a local install

**Pull request merged**
